/* Eligibility Code Generator — module: core/constants.js — education levels, mark/grade ops, post-qual timestamp map
   Part of the namespaced App.* module set. Logic is unchanged from the
   original single-file version; only wrapped for modular loading. */
(function(App){
// Each level carries TWO independent qualification axes that are generated by the
// same pipeline but kept entirely separate (their own arrays, keys and condition
// checks):
//   • Stream  — the "Subject / Stream" column. Fields: stream/ss/...   (selstreamN)
//   • Degree  — the "Degree" column.           Fields: degree/sd/...   (seldegreeN)
// `hasStream`/`hasDegree` mark which axes a level can carry (identical today; kept
// as separate flags so a level could differ in future). The Degree array name
// mirrors the Stream name with a `_Degree` suffix and `seldegree<idx>` mirrors
// `selstream<idx>` — see the axis descriptors in parsing/streams.js.
var EDU = {
  'SSC/10th':                        {idx:1,  stream:'arrSSC_Stream',        ss:'selstream1', degree:'arrSSC_Degree',        sd:'seldegree1', sm:'selmark1', sg:'selgrade1', lang:'edu_lbl_ssc',        hasStream:false, hasDegree:false},
  'HSC/12th':                        {idx:2,  stream:'arrHSC_Stream',        ss:'selstream2', degree:'arrHSC_Degree',        sd:'seldegree2', sm:'selmark2', sg:'selgrade2', lang:'edu_lbl_hsc',        hasStream:true,  hasDegree:true},
  'Graduation':                      {idx:3,  stream:'arrGraduation_Stream', ss:'selstream3', degree:'arrGraduation_Degree', sd:'seldegree3', sm:'selmark3', sg:'selgrade3', lang:'edu_lbl_graduation', hasStream:true,  hasDegree:true},
  'Post Graduation':                 {idx:4,  stream:'arrPG_Stream',         ss:'selstream4', degree:'arrPG_Degree',         sd:'seldegree4', sm:'selmark4', sg:'selgrade4', lang:'edu_lbl_pg',         hasStream:true,  hasDegree:true},
  'Professional Qualification':      {idx:5,  stream:'arrProf_Stream',       ss:'selstream5', degree:'arrProf_Degree',       sd:'seldegree5', sm:'selmark5', sg:'selgrade5', lang:'edu_lbl_proff',      hasStream:true,  hasDegree:true},
  'Post Graduation Diploma':         {idx:6,  stream:'arrPgDiploma_Stream',  ss:'selstream6', degree:'arrPgDipolma_Degree',  sd:'seldegree6', sm:'selmark6', sg:'selgrade6', lang:'edu_lbl_pg_diploma', hasStream:true,  hasDegree:true},
  'Certification':                   {idx:7,  stream:'arrCert_Stream',       ss:'selstream7', degree:'arrCert_Degree',       sd:'seldegree7', sm:'selmark7', sg:'selgrade7', lang:'edu_lbl_certif',     hasStream:true,  hasDegree:true},
  'Diploma':                         {idx:8,  stream:'arrDiploma_Stream',    ss:'selstream8', degree:'arrDiploma_Degree',    sd:'seldegree8', sm:'selmark8', sg:'selgrade8', lang:'edu_lbl_diploma',    hasStream:true,  hasDegree:true},
  'Ph.D':                            {idx:9,  stream:'arrPhD_Stream',        ss:'selstream9', degree:'arrPhD_Degree',        sd:'seldegree9', sm:'selmark9', sg:'selgrade9', lang:'edu_lbl_phd',        hasStream:true,  hasDegree:true},
  'Integrated Post Graduate Diploma':{idx:10, stream:'arrIDD_Stream', ss:'selstream10', degree:'arrIDD_Degree', sd:'seldegree10', sm:'selmark10',sg:'selgrade10',lang:'edu_lbl_idd',  hasStream:true,  hasDegree:true},
  'Others':                          {idx:11, stream:'arrOthers_Stream',     ss:'selstream11', degree:'arrOthers_Degree', sd:'seldegree11', sm:'selmark11',sg:'selgrade11',lang:'edu_lbl_others',     hasStream:true,  hasDegree:true}
};
var EDU_ALIASES = {
  'ug':'Graduation','pg':'Post Graduation','pg diploma':'Post Graduation Diploma',
  'pgd':'Post Graduation Diploma','graduation degree':'Graduation','ug degree':'Graduation',
  'post graduation degree':'Post Graduation','pg degree':'Post Graduation',
  'post graduate diploma':'Post Graduation Diploma','p.g. diploma':'Post Graduation Diploma',
  'integrated dual degree':'Integrated Post Graduate Diploma',
  'certificate':'Certification','certificate course':'Certification',
  'phd':'Ph.D','ph.d.':'Ph.D','doctorate':'Ph.D',
  'ssc':'SSC/10th','10th':'SSC/10th','10th std':'SSC/10th',
  'hsc':'HSC/12th','12th':'HSC/12th','12th std':'HSC/12th','10+2':'HSC/12th','senior secondary school':'HSC/12th','diploma degree':'Diploma'
};
// keyword-contains rules, most specific first
var EDU_KW = [
  {level:'Integrated Post Graduate Diploma', kw:['integrated post graduate','integrated pg','integrated dual']},
  {level:'Post Graduation Diploma',          kw:['post graduation diploma','post graduate diploma','pg diploma','pgd']},
  {level:'Post Graduation',                  kw:['post graduation','post graduate','p.g.','m.tech','m.e.','m.b.a','mba','m.c.a','mca','m.sc','msc','m.com','mcom','m.a.']},
  {level:'Professional Qualification',       kw:['professional qualification','professional']},
  {level:'Ph.D',                             kw:['ph.d','phd','doctorate','d.phil']},
  {level:'Certification',                    kw:['certification','certificate']},
  {level:'Diploma',                          kw:['diploma']},
  {level:'Graduation',                       kw:['graduation','graduate','b.tech','b.e.','b.sc','bsc','b.com','bcom','b.a.','bca','b.c.a','bachelor','degree']},
  {level:'HSC/12th',                         kw:['hsc','12th','class xii','class 12','higher secondary','intermediate','10+2']},
  {level:'SSC/10th',                         kw:['ssc','10th','class x','class 10','matriculation','secondary school']}
];
var EDU_ORDER = ['SSC/10th','HSC/12th','Diploma','Graduation','Post Graduation',
  'Post Graduation Diploma','Integrated Post Graduate Diploma','Certification',
  'Professional Qualification','Ph.D','Others'];
var MARK_OPS = {
  '>0%':   {php:'> 0',   err:'> 0 %'},
  '>=35%': {php:'>= 35', err:'>= 35 %'},
  '>=40%': {php:'>= 40', err:'>= 40 %'},
  '>=45%': {php:'>= 45', err:'>= 45 %'},
  '>=50%': {php:'>= 50', err:'>= 50 %'},
  '>=55%': {php:'>= 55', err:'>= 55 %'},
  '>=60%': {php:'>= 60', err:'>= 60 %'},
  '>=65%': {php:'>= 65', err:'>= 65 %'},
  '>=70%': {php:'>= 70', err:'>= 70 %'}
};
var GRADE_OPS = {
  'Any Class':   {php:"!=''",             err:'Any Class'},
  'First Class': {php:"=='First Class'",  err:'First Class'},
  'Second Class':{php:"=='Second Class'", err:'Second Class'},
  'Pass Class':  {php:"=='Pass Class'",   err:'Pass Class'}
};
// Grade hierarchy (higher rank = better). When a grade threshold is required, every
// HIGHER grade must also be accepted — e.g. "Second Class" allows First Class too.
var GRADE_RANK = {'Pass Class':1, 'Second Class':2, 'First Class':3};
// Returns the PHP grade test for a field, expanding a threshold into "this grade OR
// any higher grade". 'Any Class' stays a non-empty check.
function gradeCheck(field, gradeRaw){
  if(!gradeRaw) return null;
  if(gradeRaw==='Any Class') return field+" !=''";
  var r=GRADE_RANK[gradeRaw];
  if(r===undefined){ var go=GRADE_OPS[gradeRaw]; return go?field+' '+go.php:null; }
  var allowed=Object.keys(GRADE_RANK).filter(function(k){return GRADE_RANK[k]>=r;})
                .sort(function(a,b){return GRADE_RANK[a]-GRADE_RANK[b];});  // required grade, then higher
  var eqs=allowed.map(function(k){return field+" =='"+k+"'";});
  return eqs.length>1?'('+eqs.join(' || ')+')':eqs[0];
}

// ── POST-QUALIFICATION TIMESTAMP MAP ──────────────────────────────────────
// Maps EDU.idx -> the strtotime() variable used in work_exp_details_validations.php
// and the academic-hierarchy rank used to pick the "highest academic qualification".
//   acad > 0 : academic qualification, larger rank = higher.
//             SSC(1) < HSC(2) < Graduation(3) < (PG | PG Diploma)(4) < PhD(5)
//   acad = 0 : special qualification (Diploma / Certification / Professional / IDD)
//             — no precedence among themselves, compared against the highest academic.
var POSTQUAL_TS = {
  1: {v:'$ssctimeStr',                acad:1},
  2: {v:'$hsctimeStr',                acad:2},
  3: {v:'$graduationtimeStr',         acad:3},
  4: {v:'$pggraduationtimeStr',       acad:4},
  5: {v:'$proftimeStr',               acad:0},
  6: {v:'$pggraduationdiplomatimeStr',acad:4},
  7: {v:'$certtimeStr',               acad:0},
  8: {v:'$diplomatimeStr',            acad:0},
  9: {v:'$phdtimeStr',                acad:5},
  10:{v:'$iddtimeStr',                acad:0}
};

// Look up a normalised mark string. Returns the {php, err} descriptor from the
// static MARK_OPS table when the value is listed there; otherwise synthesises
// one for any valid >=N% / >N% / N% pattern so arbitrary percentages work.
function lookupMarkOp(mk){
  if(!mk) return null;
  if(MARK_OPS[mk]) return MARK_OPS[mk];
  var m=mk.match(/^(>=|>)?(\d{1,3})%$/);
  if(!m) return null;
  var op=m[1]||'>=';
  var n=m[2];
  return {php: op+' '+n, err: op+' '+n+' %'};
}

  // ── exports to App ──
  App.EDU = EDU;
  App.EDU_ALIASES = EDU_ALIASES;
  App.EDU_KW = EDU_KW;
  App.EDU_ORDER = EDU_ORDER;
  App.GRADE_OPS = GRADE_OPS;
  App.GRADE_RANK = GRADE_RANK;
  App.MARK_OPS = MARK_OPS;
  App.lookupMarkOp = lookupMarkOp;
  App.POSTQUAL_TS = POSTQUAL_TS;
  App.gradeCheck = gradeCheck;
})(window.App = window.App || {});
